In [1]:
import numpy as np

## **Exercice 1**

In [63]:
array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## **Exercice 2**

In [5]:
my_list = [3.14, 2.17, 0, 1, 2]
my_list = np.int64(my_list)
my_list

array([3, 2, 0, 1, 2])

## **Exercice 3**

In [9]:
matrice = np.arange(1,10)
matrice = matrice.reshape(3,3)
matrice

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Exercice 4**

In [13]:
my_mat = np.random.rand(20)
my_mat = my_mat.reshape(4,5)
my_mat

array([[0.81845273, 0.49542768, 0.12936384, 0.51519271, 0.27517557],
       [0.49369315, 0.96233699, 0.46517961, 0.68200047, 0.99995491],
       [0.10174268, 0.30910184, 0.71135203, 0.35643641, 0.35275744],
       [0.20261771, 0.1012115 , 0.99550835, 0.87885729, 0.50468585]])

## **Exerice 5**

In [14]:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1,:]

array([20, 21, 22, 23, 24])

## **Exerice 6**

In [69]:
reverse_array = np.arange(10)
reverse_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## **Exerice 7**

In [31]:
identity = np.identity(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## **Exercice 8**

In [64]:
my_new_list = np.arange(0,10)
my_new_list_mean = np.mean(my_new_list)
my_new_list_sum = np.sum(my_new_list)

In [65]:
print(f'Sum : {my_new_list_sum}')
print(f'Average : {my_new_list_mean}')

Sum : 45
Average : 4.5


## **Exerice 9**

In [37]:
numpy_element = np.arange(1,21)
numpy_element = numpy_element.reshape(4,5)
numpy_element

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## **Exerice 10**

In [61]:
odd_numbers = np.arange(10)
odd_numbers = odd_numbers[odd_numbers % 2 != 0]


In [62]:
print(odd_numbers)

[1 3 5 7 9]
