## **Exercice 1**

In [1]:
import numpy as np

In [14]:
np.random.seed(42)
t1 = np.random.rand(25).reshape(5,5)

In [15]:
t1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [37]:
t1[2:3,1:2] = 0

In [38]:
t1

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.        , 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

## **Exercice 2**

In [41]:
t2 = np.random.rand(20)
t2 = np.round(t2, 2)

In [42]:
t3 = np.random.rand(20)
t3 = np.round(t3, 2)

In [46]:
commun = []

In [47]:
for i in t2:
    for j in t3:
        if i == j:
            commun.append(i)

In [48]:
commun

[np.float64(0.77),
 np.float64(0.71),
 np.float64(0.73),
 np.float64(0.77),
 np.float64(0.12),
 np.float64(0.33),
 np.float64(0.31)]

## **Exercice 3**

In [53]:
t4 = np.random.rand(10)

In [69]:
t4

array([0.42710779, 0.81801477, 0.86073058, 0.00695213, 0.5107473 ,
       0.417411  , 0.22210781, 0.11986537, 0.33761517, 0.9429097 ])

In [70]:
ascending = np.sort(t4)

In [71]:
ascending

array([0.00695213, 0.11986537, 0.22210781, 0.33761517, 0.417411  ,
       0.42710779, 0.5107473 , 0.81801477, 0.86073058, 0.9429097 ])

In [72]:
descending = np.sort(t4)[::-1]

In [73]:
descending

array([0.9429097 , 0.86073058, 0.81801477, 0.5107473 , 0.42710779,
       0.417411  , 0.33761517, 0.22210781, 0.11986537, 0.00695213])

## **Exercice 4**

In [74]:
t5 = np.random.rand(25).reshape(5,5)

In [77]:
print(f'Cette matrice est de rang {t5.shape[0]}')

Cette matrice est de rang 5


## **Exercice 5**

In [78]:
# Création d'une matrice 5x5 remplie de 1
arr = np.ones((5, 5), dtype=int)

# Remplacement de l'intérieur par des 0
arr[1:-1, 1:-1] = 0


In [80]:
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
