In [1]:
import numpy as np

## **Exercice 1** 

In [3]:
t1 = np.random.rand(25)
t1 = t1.reshape(5,5)
t1

array([[0.2437235 , 0.87386707, 0.15357824, 0.88768456, 0.19234012],
       [0.29157627, 0.62796658, 0.54934484, 0.28909317, 0.39338031],
       [0.26805809, 0.03713298, 0.88111589, 0.00358803, 0.33157398],
       [0.33444928, 0.47128615, 0.61058643, 0.96885974, 0.68171897],
       [0.81418463, 0.44773178, 0.01682614, 0.40271423, 0.22584314]])

In [7]:
print(f"Max :{round(t1.max(),3)}")

Max :0.969


In [8]:
print(f"Min :{round(t1.min(),3)}")

Min :0.004


## **Exercice 2**

In [9]:
mat = np.random.rand(3, 3)
mat_norm = (mat - mat.mean()) / mat.std()
mat_norm

array([[ 1.05743848, -0.92923292,  1.01885816],
       [-0.60216613,  1.40332366, -1.20780409],
       [-1.23808369, -0.26734444,  0.76501097]])

## **Exercice 3**

In [ ]:
t2 = np.linspace(0,10,50)
t2

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## **Exercice 4**

In [25]:
t3 = np.random.rand(15).reshape(5,3)
t4 = np.random.rand(6).reshape(3,2)

In [29]:
t3@t4

array([[0.8758958 , 1.31539424],
       [0.1974552 , 0.24604494],
       [0.79607605, 1.11805674],
       [1.21898128, 1.67683054],
       [0.68071806, 0.86727767]])

## **Exercice 5**

In [30]:
t5 = np.random.rand(21)*100
t5 = t5.reshape(7,3)
t5

array([[92.46351866, 17.63188432, 74.55279192],
       [57.0514151 , 86.35092633, 64.57020245],
       [ 2.56653558, 56.65734718, 11.78612794],
       [ 7.42652508, 72.41112063, 93.50222416],
       [97.45778035, 89.85566398, 98.56901792],
       [23.16631809, 94.70505037, 29.25159047],
       [89.51065269, 87.42412842, 86.35588517]])

In [31]:
t6 = np.random.rand(18)*100
t6 = t6.reshape(3,6)
t6

array([[29.88236294,  5.2819335 , 21.88077714, 66.24556939, 21.42347734,
        14.52563873],
       [20.42359652, 26.19481524, 25.46784286, 63.2083552 , 28.12313478,
        77.15184956],
       [16.79676549, 54.62550356, 69.55006835, 12.73897873,  2.20145683,
        15.73087884]])

In [32]:
t5@t6

array([[ 4375.3806769 ,  5022.7339095 ,  7657.3714789 ,  8189.50727816,
         2640.87870816,  3876.20509142],
       [ 4552.99811881,  6090.4681661 ,  7938.36311648, 10060.06193669,
         3792.84695083,  8506.58795421],
       [ 1431.80977325,  2141.50818562,  2318.82421184,  3901.38256907,
         1674.31297946,  4593.90584512],
       [ 3271.35256083,  7043.62841672,  8509.73926339,  6260.08506079,
         2401.37080659,  7165.39906556],
       [ 6403.08526808,  8252.90027086, 11276.36383701, 13391.44349816,
         4831.90293445,  9898.74445663],
       [ 3117.81416744,  4201.02710816,  4953.28050104,  7893.45178436,
         3224.1020998 ,  8103.32859166],
       [ 5910.8044874 ,  7480.08191966, 10191.12432456, 12555.70530047,
         4566.3787387 ,  9403.58657442]])