## **Exercice 1** 

In [81]:
import numpy as np

In [85]:
mat = np.round(np.random.rand(16)*100,2)

In [87]:
mat =  mat.reshape(4,4)

In [89]:
mat

array([[90.04, 63.31, 33.9 , 34.92],
       [72.6 , 89.71, 88.71, 77.99],
       [64.2 ,  8.41, 16.16, 89.86],
       [60.64,  0.92, 10.15, 66.35]])

In [90]:
# Extraction des éléments diagonaux
diag_elements = np.diag(mat)

print("Éléments diagonaux :")
print(diag_elements)

# Création d'une matrice diagonale à partir de ces éléments
diag_matrix = np.diag(diag_elements)

print("\nMatrice diagonale :")
print(diag_matrix)

Éléments diagonaux :
[90.04 89.71 16.16 66.35]

Matrice diagonale :
[[90.04  0.    0.    0.  ]
 [ 0.   89.71  0.    0.  ]
 [ 0.    0.   16.16  0.  ]
 [ 0.    0.    0.   66.35]]


## **Exercice 2**

In [91]:
nb = np.random.rand(20)

In [97]:
rand_array = np.random.rand(20)
rand_array[rand_array > 0.5] = -1
rand_array

array([-1.        , -1.        , -1.        , -1.        , -1.        ,
        0.49251769,  0.19524299, -1.        ,  0.28077236,  0.02431597,
       -1.        ,  0.17711068, -1.        , -1.        , -1.        ,
        0.3701587 ,  0.01545662, -1.        ,  0.42818415, -1.        ])

## **Exerice 3**

In [98]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
nb_norm = scaler.fit_transform(nb.reshape(-1, 1)).flatten()
nb_norm

array([-1.75341812, -1.16386661,  0.30455966,  0.8464726 ,  0.69530953,
       -0.92364492,  0.92325428, -0.87451219, -0.54083319,  1.05313717,
        0.68649592,  1.44201153,  0.71670281,  0.37865676, -1.41798813,
       -0.38065284, -0.76869985, -0.84899698,  1.91058651, -0.28457394])

## **Exercice 4**

In [101]:
pearson_corr = np.corrcoef(t2, t3)[0, 1]
pearson_corr

np.float64(-0.2376327724356357)

## **Exercice 5**

In [ ]:
import matplotlib.pyplot as plt

np.random.seed(0)
n_days = 15
days = np.arange(n_days)
ts_values = np.random.rand(n_days)  # valeurs aléatoires

# Ajustement d'une droite de tendance linéaire
slope, intercept = np.polyfit(days, ts_values, 1)
trend = slope * days + intercept

# Coefficient de corrélation de Pearson
pearson_r = np.corrcoef(days, ts_values)[0, 1]

# Affichage / tracé
plt.figure(figsize=(8, 4))
plt.plot(days, ts_values, 'o-', label='Série temporelle')
plt.plot(days, trend, 'r--', label=f'Droite de tendance (pente={slope:.3f})')
plt.xlabel('Jour')
plt.ylabel('Valeur')
plt.title('Série temporelle sur 15 jours et droite de tendance')
plt.legend()
plt.grid(True)
plt.show()

print(f"Coefficient de corrélation de Pearson (jours vs valeurs) : {pearson_r:.4f}")

# Formule du coefficient de corrélation de Pearson :
# r = sum((x - mean(x)) * (y - mean(y))) / ( sqrt(sum((x - mean(x))**2)) * sqrt(sum((y - mean(y))**2)) )